Do not install and run code-analysis on Plone 5.0.
Latest failure is:

```
While:
  Installing.
  Getting section code-analysis.
  Initializing section code-analysis.
  Installing recipe plone.recipe.codeanalysis.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/zc/buildout/buildout.py", line 2174, in main
    getattr(buildout, command)(args)
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/zc/buildout/buildout.py", line 701, in install
    [self[part]['recipe'] for part in install_parts]
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/zc/buildout/buildout.py", line 1324, in __getitem__
    options._initialize()
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/zc/buildout/buildout.py", line 1432, in _initialize
    self.initialize()
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/zc/buildout/buildout.py", line 1438, in initialize
    recipe_class = _install_and_load(reqs, 'zc.buildout', entry, buildout)
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/zc/buildout/buildout.py", line 1388, in _install_and_load
    allow_hosts=buildout._allow_hosts
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/zc/buildout/easy_install.py", line 957, in install
    return installer.install(specs, working_set)
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/zc/buildout/easy_install.py", line 703, in install
    req = self._constrain(current_requirement)
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/zc/buildout/easy_install.py", line 657, in _constrain
    requirement)
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/zc/buildout/easy_install.py", line 1614, in _constrained_requirement
    str(requirement) + ',' + constraint
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3148, in parse
    req, = parse_requirements(s)
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3094, in parse_requirements
    yield Requirement(line)
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3103, in __init__
    raise RequirementParseError(str(e))
RequirementParseError: Invalid requirement, parse error at "',<5.0.0'"
```

See https://travis-ci.org/github/collective/collective.easyform/jobs/743972394
Good luck figuring that one out.

code-analysis passes on all other jobs, so we're fine.