Revert "fix encoding of utf8 headers"
This reverts commit 2ec065ca4f97c03bfdb6128c230bec5b83b38e65.

It has lots of test failures like this:

```
Error in test test_selectiveFieldMailing (collective.easyform.tests.testMailer.TestFunctions)
Traceback (most recent call last):
  File "/Users/maurits/.pyenv/versions/3.8.20/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/Users/maurits/.pyenv/versions/3.8.20/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/Users/maurits/.pyenv/versions/3.8.20/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/Users/maurits/community/collective.easyform-3x/src/collective/easyform/tests/testMailer.py", line 381, in test_selectiveFieldMailing
    mailer.onSuccess(fields, request)
  File "/Users/maurits/community/collective.easyform-3x/src/collective/easyform/actions.py", line 519, in onSuccess
    mailtext = self.get_mail_text(fields, request, context)
  File "/Users/maurits/community/collective.easyform-3x/src/collective/easyform/actions.py", line 514, in get_mail_text
    return outer.as_string()
  File "/Users/maurits/.pyenv/versions/3.8.20/lib/python3.8/email/message.py", line 158, in as_string
    g.flatten(self, unixfrom=unixfrom)
  File "/Users/maurits/.pyenv/versions/3.8.20/lib/python3.8/email/generator.py", line 118, in flatten
    self._write(msg)
  File "/Users/maurits/.pyenv/versions/3.8.20/lib/python3.8/email/generator.py", line 201, in _write
    self._write_headers(msg)
  File "/Users/maurits/.pyenv/versions/3.8.20/lib/python3.8/email/generator.py", line 228, in _write_headers
    folded = self.policy.fold(h, v)
  File "/Users/maurits/.pyenv/versions/3.8.20/lib/python3.8/email/_policybase.py", line 334, in fold
    return self._fold(name, value, sanitize=True)
  File "/Users/maurits/.pyenv/versions/3.8.20/lib/python3.8/email/_policybase.py", line 377, in _fold
    parts.append(h.encode(linesep=self.linesep, maxlinelen=maxlinelen))
AttributeError: 'bytes' object has no attribute 'encode'
```